### ISSUE TITLE
Overriding meta replicas is not working

### ISSUE THREAD

**Issue by Ultrafenrir** [banzaicloud/thanos-operator#61] opened 2020-10-28 11:56 UTC
**Describe the bug**
If u will try to setup the following config

```
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos
spec:
  clusterDomain: platform-rke-test-env
  enableRecreateWorkloadOnImmutableFieldChange: true
  query:
    metaOverrides:
      replicas: "3"
```

u still get only 1 pod of query

**Steps to reproduce the issue:**
Set the 
```
  query:
    metaOverrides:
      replicas: "3"
```
**Expected behavior**
U should be able to control the number of instances for query and queryFrontend 

**Additional context**
With query there are a strange behaviour ,  every time i deploy query even without

```
   query:
    metaOverrides:
      replicas: "3"

```

i getting 2 instances of query until one of them don't pass readiness probe, then the second one is marking as "removing"
And if i set replicas into 2 or 3 , i will get 3 instances of query on startup, but then 2 of them will be removed.

The same thing with queryFrontend

**Comment by craigfurman** [comment] 2020-11-11 16:13
I think my issue https://github.com/banzaicloud/thanos-operator/issues/69 might be a duplicate of this, only I would expect `deploymentOverrides` to be the field we set replicas in, not `metaOverrides`. In https://github.com/banzaicloud/thanos-operator/issues/69 I point to a line of code that hardcodes the replica count of the operator-generated Deployments.

**Comment by bshifter** [comment] 2020-11-11 17:23
This issue is fixed in upstream, you are now able to override replicas through metaOverrides and/or statefulsetOverrides.

**Closed by bshifter** 2020-11-11 17:23 UTC
Labels: bug
